using Microsoft.EntityFrameworkCore;
using VSky.Application.Common.Interfaces;
using VSky.Application.Features.Analytics;
using VSky.Application.Features.StorefrontCatalog;
using VSky.Domain.Entities;
using VSky.Domain.Enums;

namespace VSky.Infrastructure.Storefront;

/// <summary>
/// Resolves the four <see cref="AutoGeneratedRowRule"/> product rows (WO-98) consumed by the dynamic
/// storefront home (WO-96). Every rule returns <b>published</b> products only (soft-deleted rows are
/// already excluded by the global query filter) as compact <see cref="StorefrontProductSummaryDto"/>
/// cards, with the product-level media the summary needs eager-loaded exactly as the storefront listing
/// handlers load it.
/// </summary>
public class AutoGeneratedRowService : IAutoGeneratedRowService
{
    private const int MinCount = 1;
    private const int MaxAllowedCount = 50;

    private readonly IApplicationDbContext _db;
    private readonly IDateTimeProvider _clock;

    public AutoGeneratedRowService(IApplicationDbContext db, IDateTimeProvider clock)
    {
        _db = db;
        _clock = clock;
    }

    public Task<IReadOnlyList<StorefrontProductSummaryDto>> ResolveAsync(
        AutoGeneratedRowRule rule, int maxCount, CancellationToken ct)
    {
        var take = Math.Clamp(maxCount, MinCount, MaxAllowedCount);
        return rule switch
        {
            AutoGeneratedRowRule.NewArrivals => NewArrivalsAsync(take, ct),
            AutoGeneratedRowRule.BestSellers => BestSellersAsync(take, ct),
            AutoGeneratedRowRule.OnSale => OnSaleAsync(take, ct),
            AutoGeneratedRowRule.Featured => FeaturedAsync(take, ct),
            _ => Task.FromResult<IReadOnlyList<StorefrontProductSummaryDto>>(
                Array.Empty<StorefrontProductSummaryDto>()),
        };
    }

    /// <summary>Published products, most recently created first.</summary>
    private async Task<IReadOnlyList<StorefrontProductSummaryDto>> NewArrivalsAsync(int take, CancellationToken ct)
    {
        var products = await PublishedSummaries()
            .OrderByDescending(p => p.CreatedOnUtc)
            .ThenBy(p => p.Name)
            .Take(take)
            .ToListAsync(ct);
        return Project(products);
    }

    /// <summary>Featured products in curated order (<see cref="Product.FeaturedDisplayOrder"/> then name).</summary>
    private async Task<IReadOnlyList<StorefrontProductSummaryDto>> FeaturedAsync(int take, CancellationToken ct)
    {
        var products = await PublishedSummaries()
            .Where(p => p.IsFeatured)
            .OrderBy(p => p.FeaturedDisplayOrder)
            .ThenBy(p => p.Name)
            .Take(take)
            .ToListAsync(ct);
        return Project(products);
    }

    /// <summary>
    /// Published products ranked by units sold (descending) over orders whose money is actually
    /// recognised — the same "captured / partially-refunded, not cancelled, not an abandoned redirect
    /// shell" predicate the analytics revenue reports use (<see cref="RevenueOrders.WithRecognisedRevenue"/>).
    /// Units = the sum of <see cref="OrderLineItem.Quantity"/> across those orders. Ties break by product id
    /// at the database boundary (deterministic when the top-N cuts a tie) and by name for the final display.
    /// </summary>
    private async Task<IReadOnlyList<StorefrontProductSummaryDto>> BestSellersAsync(int take, CancellationToken ct)
    {
        var paidOrders = _db.Orders.AsNoTracking().WithRecognisedRevenue();

        var ranked = await _db.OrderLineItems
            .AsNoTracking()
            .Where(li => paidOrders.Any(o => o.Id == li.OrderId))
            .Where(li => _db.Products.Any(p => p.Id == li.ProductId && p.IsPublished))
            .GroupBy(li => li.ProductId)
            .Select(g => new { ProductId = g.Key, Units = g.Sum(x => x.Quantity) })
            .OrderByDescending(x => x.Units)
            .ThenBy(x => x.ProductId)
            .Take(take)
            .ToListAsync(ct);

        if (ranked.Count == 0)
            return Array.Empty<StorefrontProductSummaryDto>();

        var ids = ranked.Select(r => r.ProductId).ToList();
        var unitsById = ranked.ToDictionary(r => r.ProductId, r => r.Units);

        var products = await PublishedSummaries()
            .Where(p => ids.Contains(p.Id))
            .ToListAsync(ct);

        return products
            .OrderByDescending(p => unitsById[p.Id])
            .ThenBy(p => p.Name)
            .Select(StorefrontProductSummaryDto.From)
            .ToList();
    }

    /// <summary>
    /// Published products currently on sale. "On sale" here = the product is the target of an active,
    /// in-window, auto-applied catalog <see cref="Discount"/> — either a Product-scoped discount naming it,
    /// or a Category-scoped discount on one of its categories. Coupon-gated discounts are excluded (they only
    /// reduce a price once a code is entered, so the product is not yet visibly on sale), mirroring the
    /// discount engine's own gate. Ordered by the largest applicable single-unit reduction (its "sale
    /// magnitude") descending, then by price. NOTE: there is no compare-at / old-price field on Product in
    /// this codebase, so an active Discount is the only faithful product-level sale signal; the magnitude is
    /// the single largest applicable auto-discount (not the stacked total) and is 0 for products that have no
    /// product-level Price.
    /// </summary>
    private async Task<IReadOnlyList<StorefrontProductSummaryDto>> OnSaleAsync(int take, CancellationToken ct)
    {
        var now = _clock.UtcNow;

        // Active, in-window, auto-applied (non-coupon) product/category discounts — the storefront's sale signal.
        var rawRules = await _db.Discounts
            .AsNoTracking()
            .Where(d => d.IsActive && !d.RequiresCoupon)
            .Where(d => d.StartDateUtc == null || d.StartDateUtc <= now)
            .Where(d => d.EndDateUtc == null || d.EndDateUtc >= now)
            .Where(d => d.Scope == DiscountScope.Product || d.Scope == DiscountScope.Category)
            .Select(d => new { d.Scope, d.Type, d.Value, d.ProductId, d.CategoryId })
            .ToListAsync(ct);

        var productRules = rawRules
            .Where(d => d.Scope == DiscountScope.Product && d.ProductId.HasValue)
            .Select(d => new SaleRule(d.Type, d.Value, d.ProductId!.Value))
            .GroupBy(r => r.KeyId)
            .ToDictionary(g => g.Key, g => g.ToList());

        var categoryRules = rawRules
            .Where(d => d.Scope == DiscountScope.Category && d.CategoryId.HasValue)
            .Select(d => new SaleRule(d.Type, d.Value, d.CategoryId!.Value))
            .ToList();

        if (productRules.Count == 0 && categoryRules.Count == 0)
            return Array.Empty<StorefrontProductSummaryDto>();

        var directIds = productRules.Keys.ToHashSet();
        var discountedCategoryIds = categoryRules.Select(r => r.KeyId).ToHashSet();

        // Light projection of the candidate published products (id + price + their category ids) so each
        // product's sale magnitude can be scored without materialising full entities for the whole set.
        var candidates = await _db.Products
            .AsNoTracking()
            .Where(p => p.IsPublished)
            .Where(p => directIds.Contains(p.Id)
                        || p.ProductCategories.Any(pc => discountedCategoryIds.Contains(pc.CategoryId)))
            .Select(p => new
            {
                p.Id,
                p.Price,
                CategoryIds = p.ProductCategories.Select(pc => pc.CategoryId).ToList(),
            })
            .ToListAsync(ct);

        if (candidates.Count == 0)
            return Array.Empty<StorefrontProductSummaryDto>();

        var ordered = candidates
            .Select(c => new
            {
                c.Id,
                c.Price,
                Magnitude = SaleMagnitude(c.Id, c.Price, c.CategoryIds, productRules, categoryRules),
            })
            .OrderByDescending(x => x.Magnitude)
            .ThenBy(x => x.Price == null) // priced products before those with no product-level price
            .ThenBy(x => x.Price)
            .ThenBy(x => x.Id)
            .Take(take)
            .ToList();

        var orderedIds = ordered.Select(x => x.Id).ToList();
        var rank = orderedIds
            .Select((id, index) => (id, index))
            .ToDictionary(t => t.id, t => t.index);

        var products = await PublishedSummaries()
            .Where(p => orderedIds.Contains(p.Id))
            .ToListAsync(ct);

        return products
            .OrderBy(p => rank[p.Id])
            .Select(StorefrontProductSummaryDto.From)
            .ToList();
    }

    /// <summary>
    /// The largest single-unit reduction any applicable auto-discount grants a product: a percentage of its
    /// price, or a fixed amount capped at its price (mirrors <c>DiscountService.ComputeReduction</c> at a
    /// single-unit base). Returns 0 when the product has no product-level price to reduce.
    /// </summary>
    private static decimal SaleMagnitude(
        Guid productId,
        decimal? price,
        List<Guid> productCategoryIds,
        IReadOnlyDictionary<Guid, List<SaleRule>> productRules,
        IReadOnlyList<SaleRule> categoryRules)
    {
        var basePrice = price ?? 0m;
        if (basePrice <= 0m)
            return 0m;

        var best = 0m;

        if (productRules.TryGetValue(productId, out var direct))
        {
            foreach (var rule in direct)
                best = Math.Max(best, Reduction(rule, basePrice));
        }

        if (categoryRules.Count > 0 && productCategoryIds.Count > 0)
        {
            var categoryIds = productCategoryIds.ToHashSet();
            foreach (var rule in categoryRules)
            {
                if (categoryIds.Contains(rule.KeyId))
                    best = Math.Max(best, Reduction(rule, basePrice));
            }
        }

        return best;
    }

    private static decimal Reduction(SaleRule rule, decimal basePrice) =>
        rule.Type == DiscountType.Percentage
            ? basePrice * (rule.Value / 100m)
            : Math.Min(rule.Value, basePrice);

    /// <summary>The published-products query pre-loaded with the product-level media a summary card needs.</summary>
    private IQueryable<Product> PublishedSummaries() =>
        _db.Products
            .AsNoTracking()
            .AsSplitQuery()
            .Where(p => p.IsPublished)
            .Include(p => p.Pictures.Where(i => i.ProductVariantId == null))
                .ThenInclude(pic => pic.Media);

    private static IReadOnlyList<StorefrontProductSummaryDto> Project(IEnumerable<Product> products) =>
        products.Select(StorefrontProductSummaryDto.From).ToList();

    /// <summary>A flattened sale-discount rule keyed by the id it targets (a product id or a category id).</summary>
    private sealed record SaleRule(DiscountType Type, decimal Value, Guid KeyId);
}
