using System.Text.Json;
using System.Text.Json.Serialization;
using VSky.Application.Features.CmsBanners;
using VSky.Application.Features.CmsBlog;
using VSky.Application.Features.FeaturedContent;
using VSky.Application.Features.StorefrontCatalog;
using VSky.Domain.Entities;
using VSky.Domain.Enums;

namespace VSky.Application.Features.CmsHomeSections;

/// <summary>
/// Typed, type-agnostic configuration for a home page section (WO-96), serialized to the entity's
/// <see cref="CMSHomePageSection.Configuration"/> JSON column. Every field is nullable so a payload only
/// carries what its section type needs; deserialization is tolerant of missing/extra fields.
/// </summary>
public class HomeSectionConfig
{
    /// <summary>Default location key resolved for a <see cref="HomePageSectionType.HeroBanner"/> when none is supplied.</summary>
    public const string DefaultHeroBannerLocation = "home-hero";

    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter() },
    };

    /// <summary>Maximum number of items the section should surface (categories / products / posts). Clamped at resolve time.</summary>
    public int? MaxItems { get; set; }

    /// <summary>For <see cref="HomePageSectionType.ProductRow"/>: "Collection" (curated collection) or "Auto" (rule-generated).</summary>
    public string? ProductRowSource { get; set; }

    /// <summary>For a Collection-sourced product row: the WO-97 collection to render.</summary>
    public Guid? CollectionId { get; set; }

    /// <summary>For an Auto-sourced product row: the WO-98 rule that generates the row.</summary>
    public AutoGeneratedRowRule? Rule { get; set; }

    /// <summary>For <see cref="HomePageSectionType.HeroBanner"/>: the banner display location (defaults to "home-hero").</summary>
    public string? BannerLocation { get; set; }

    /// <summary>For <see cref="HomePageSectionType.CustomHtmlBlock"/>: the raw HTML to render.</summary>
    public string? Html { get; set; }

    /// <summary>
    /// Applies type-specific defaults so the stored config is self-describing: a hero banner always resolves
    /// to a concrete location. Mutates and returns this instance.
    /// </summary>
    public HomeSectionConfig Normalized(HomePageSectionType sectionType)
    {
        if (sectionType == HomePageSectionType.HeroBanner && string.IsNullOrWhiteSpace(BannerLocation))
            BannerLocation = DefaultHeroBannerLocation;
        return this;
    }

    /// <summary>Serializes a config to the JSON stored in <see cref="CMSHomePageSection.Configuration"/> (null → null).</summary>
    public static string? Serialize(HomeSectionConfig? config) =>
        config is null ? null : JsonSerializer.Serialize(config, JsonOptions);

    /// <summary>
    /// Deserializes the stored JSON back into a config, tolerating null/blank/malformed content by returning an
    /// empty config rather than throwing (AC — a broken config never breaks a read).
    /// </summary>
    public static HomeSectionConfig Deserialize(string? json)
    {
        if (string.IsNullOrWhiteSpace(json))
            return new HomeSectionConfig();
        try
        {
            return JsonSerializer.Deserialize<HomeSectionConfig>(json, JsonOptions) ?? new HomeSectionConfig();
        }
        catch (JsonException)
        {
            return new HomeSectionConfig();
        }
    }
}

/// <summary>Full admin view of a configurable home page section (WO-96), with its config deserialized from JSON.</summary>
public class CmsHomeSectionDto
{
    public Guid Id { get; set; }
    public HomePageSectionType SectionType { get; set; }
    public string DisplayName { get; set; } = string.Empty;
    public int DisplayOrder { get; set; }
    public bool IsEnabled { get; set; }

    /// <summary>The typed configuration deserialized from the entity's JSON column (never null; empty when unset).</summary>
    public HomeSectionConfig Config { get; set; } = new();

    public static CmsHomeSectionDto From(CMSHomePageSection e) => new()
    {
        Id = e.Id,
        SectionType = e.SectionType,
        DisplayName = e.DisplayName,
        DisplayOrder = e.DisplayOrder,
        IsEnabled = e.IsEnabled,
        Config = HomeSectionConfig.Deserialize(e.Configuration),
    };
}

/// <summary>
/// Public storefront home payload (backend half of WO-100): the ordered, enabled sections with each section's
/// data already resolved by type. An empty <see cref="Sections"/> list is a valid response (empty-state home).
/// </summary>
public class StorefrontHomeDto
{
    public List<StorefrontHomeSectionDto> Sections { get; set; } = new();
}

/// <summary>
/// One resolved storefront home section. Only the payload matching <see cref="Type"/> is populated; the rest
/// stay null so the client renders each section by its type.
/// </summary>
public class StorefrontHomeSectionDto
{
    public Guid Id { get; set; }
    public HomePageSectionType Type { get; set; }
    public string DisplayName { get; set; } = string.Empty;
    public HomeSectionConfig Config { get; set; } = new();

    /// <summary>HeroBanner: active banners for the configured location.</summary>
    public IReadOnlyList<CmsBannerPublicDto>? Banners { get; set; }

    /// <summary>FeaturedCategories: the featured category cards (bounded by MaxItems).</summary>
    public IReadOnlyList<FeaturedCategoryDto>? Categories { get; set; }

    /// <summary>ProductRow: the resolved product cards (collection- or rule-sourced, bounded by MaxItems).</summary>
    public IReadOnlyList<StorefrontProductSummaryDto>? Products { get; set; }

    /// <summary>BlogPostsRow: recent published blog posts (bounded by MaxItems).</summary>
    public IReadOnlyList<CmsBlogPostDto>? Posts { get; set; }

    /// <summary>CustomHtmlBlock: the raw HTML to render.</summary>
    public string? Html { get; set; }
}
