using MediatR;
using Microsoft.EntityFrameworkCore;
using VSky.Application.Common.Interfaces;
using VSky.Application.Features.CmsBanners;
using VSky.Application.Features.CmsBlog;
using VSky.Application.Features.CmsProductCollections;
using VSky.Application.Features.FeaturedContent;
using VSky.Application.Features.StorefrontCatalog;
using VSky.Domain.Enums;

namespace VSky.Application.Features.CmsHomeSections;

/// <summary>
/// Public storefront home read (backend half of WO-100): returns the ordered, enabled sections with each
/// section's data resolved by type. Disabled and soft-deleted sections are excluded; an empty section list is
/// a valid, non-error response. Per-type data is resolved by reusing the existing feature queries
/// (banners WO-55, featured categories WO-98, product collections WO-97, blog WO-54) plus the auto-generated
/// row service (WO-98), so this endpoint owns no duplicate projection logic.
/// </summary>
public record GetStorefrontHomeQuery() : IRequest<StorefrontHomeDto>;

public class GetStorefrontHomeQueryHandler : IRequestHandler<GetStorefrontHomeQuery, StorefrontHomeDto>
{
    // Fallback item count when a section leaves MaxItems unset; upper bound guards an over-large row.
    private const int DefaultMaxItems = 12;
    private const int MaxItemsCeiling = 50;

    private readonly IApplicationDbContext _db;
    private readonly ISender _mediator;
    private readonly IAutoGeneratedRowService _autoRows;

    public GetStorefrontHomeQueryHandler(IApplicationDbContext db, ISender mediator, IAutoGeneratedRowService autoRows)
    {
        _db = db;
        _mediator = mediator;
        _autoRows = autoRows;
    }

    public async Task<StorefrontHomeDto> Handle(GetStorefrontHomeQuery request, CancellationToken cancellationToken)
    {
        var sections = await _db.CMSHomePageSections
            .AsNoTracking()
            .Where(s => s.IsEnabled)
            .OrderBy(s => s.DisplayOrder)
            .ThenBy(s => s.Id)
            .ToListAsync(cancellationToken);

        var response = new StorefrontHomeDto();

        foreach (var section in sections)
        {
            var config = HomeSectionConfig.Deserialize(section.Configuration);
            var dto = new StorefrontHomeSectionDto
            {
                Id = section.Id,
                Type = section.SectionType,
                DisplayName = section.DisplayName,
                Config = config,
            };

            switch (section.SectionType)
            {
                case HomePageSectionType.HeroBanner:
                    var location = string.IsNullOrWhiteSpace(config.BannerLocation)
                        ? HomeSectionConfig.DefaultHeroBannerLocation
                        : config.BannerLocation!.Trim();
                    dto.Banners = await _mediator.Send(new GetActiveBannersQuery(location), cancellationToken);
                    break;

                case HomePageSectionType.FeaturedCategories:
                    var categories = await _mediator.Send(new ListFeaturedCategoriesQuery(), cancellationToken);
                    dto.Categories = Limit(categories, config.MaxItems);
                    break;

                case HomePageSectionType.ProductRow:
                    dto.Products = await ResolveProductRowAsync(config, cancellationToken);
                    break;

                case HomePageSectionType.BlogPostsRow:
                    var posts = await _mediator.Send(new ListPublishedBlogPostsQuery(1, ClampMax(config.MaxItems)), cancellationToken);
                    dto.Posts = posts.Items;
                    break;

                case HomePageSectionType.CustomHtmlBlock:
                    dto.Html = config.Html;
                    break;
            }

            response.Sections.Add(dto);
        }

        return response;
    }

    /// <summary>
    /// Resolves a ProductRow's cards: an "Auto" source runs the WO-98 rule via <see cref="IAutoGeneratedRowService"/>;
    /// otherwise (Collection source) the configured WO-97 collection's ordered published products are returned.
    /// A missing/empty collection reference yields an empty row.
    /// </summary>
    private async Task<IReadOnlyList<StorefrontProductSummaryDto>> ResolveProductRowAsync(
        HomeSectionConfig config, CancellationToken cancellationToken)
    {
        if (string.Equals(config.ProductRowSource, "Auto", StringComparison.OrdinalIgnoreCase))
        {
            var rule = config.Rule ?? AutoGeneratedRowRule.NewArrivals;
            return await _autoRows.ResolveAsync(rule, ClampMax(config.MaxItems), cancellationToken);
        }

        if (config.CollectionId is Guid collectionId && collectionId != Guid.Empty)
        {
            var products = await _mediator.Send(new GetCollectionProductsQuery(collectionId), cancellationToken);
            return Limit(products, config.MaxItems);
        }

        return Array.Empty<StorefrontProductSummaryDto>();
    }

    /// <summary>Resolves MaxItems to a concrete, bounded page size (default when unset, clamped to 1..50).</summary>
    private static int ClampMax(int? maxItems)
    {
        var value = maxItems.GetValueOrDefault(DefaultMaxItems);
        if (value <= 0)
            value = DefaultMaxItems;
        return Math.Min(value, MaxItemsCeiling);
    }

    /// <summary>Trims an already-materialised list to MaxItems when set; returns it unchanged otherwise.</summary>
    private static IReadOnlyList<T> Limit<T>(IReadOnlyList<T> items, int? maxItems)
    {
        if (maxItems is int max && max > 0 && items.Count > max)
            return items.Take(max).ToList();
        return items;
    }
}
