namespace VSky.Domain.Enums;

/// <summary>Publish lifecycle for CMS pages and blog posts (WO-54).</summary>
public enum CmsContentStatus
{
    Draft = 0,
    Published = 1,
    Archived = 2,
}

/// <summary>Home page section types rendered by the dynamic storefront home (WO-96 / WO-100).</summary>
public enum HomePageSectionType
{
    HeroBanner = 0,
    FeaturedCategories = 1,
    ProductRow = 2,
    BlogPostsRow = 3,
    CustomHtmlBlock = 4,
}

/// <summary>Rule that resolves an auto-generated product row at request time (WO-98).</summary>
public enum AutoGeneratedRowRule
{
    NewArrivals = 0,
    BestSellers = 1,
    OnSale = 2,
    Featured = 3,
}

/// <summary>Lifecycle of a newsletter subscription (WO-56).</summary>
public enum NewsletterSubscriptionStatus
{
    Pending = 0,
    Subscribed = 1,
    Unsubscribed = 2,
}
