using VSky.Application.Features.StorefrontCatalog;
using VSky.Domain.Enums;

namespace VSky.Application.Common.Interfaces;

/// <summary>
/// Resolves an auto-generated storefront product row (WO-98) from an <see cref="AutoGeneratedRowRule"/>
/// into a bounded, published set of product-summary cards, already ordered for display. Consumed
/// server-side by the dynamic home endpoint (WO-96) to materialise the "New Arrivals" / "Best Sellers" /
/// "On Sale" / "Featured" rows without the storefront having to know how each rule is computed.
/// </summary>
public interface IAutoGeneratedRowService
{
    /// <summary>
    /// Returns up to <paramref name="maxCount"/> published <see cref="StorefrontProductSummaryDto"/> cards
    /// for the given <paramref name="rule"/>. <paramref name="maxCount"/> is clamped to a sane 1..50 range.
    /// </summary>
    Task<IReadOnlyList<StorefrontProductSummaryDto>> ResolveAsync(
        AutoGeneratedRowRule rule, int maxCount, CancellationToken ct);
}
