using System.Net;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using VSky.Application.Common.Interfaces;
using VSky.Infrastructure.Alerts;
using VSky.Infrastructure.Credentials;
using VSky.Infrastructure.Currencies;
using VSky.Infrastructure.Inventory;
using VSky.Infrastructure.Persistence;
using VSky.Infrastructure.Routing;
using VSky.Infrastructure.Pricing;
using VSky.Infrastructure.Shipping;
using VSky.Infrastructure.Shipping.Carriers;
using VSky.Infrastructure.Payments;
using VSky.Infrastructure.Payments.Adapters;
using VSky.Infrastructure.Tax;
using VSky.Infrastructure.Tax.Providers;
using VSky.Infrastructure.Documents;
using VSky.Infrastructure.Checkout;
using VSky.Infrastructure.BackgroundTasks;
using VSky.Infrastructure.BackgroundTasks.Workers;
using VSky.Infrastructure.Email;
using VSky.Infrastructure.Security;
using VSky.Infrastructure.Services;
using VSky.Infrastructure.Settings;
using VSky.Infrastructure.Storage;
using VSky.Infrastructure.Storefront;
using VSky.Infrastructure.Seo;

namespace VSky.Infrastructure;

/// <summary>Registers Infrastructure-layer services: EF Core context, clock, database initializer.</summary>
public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services, IConfiguration configuration)
    {
        var connectionString = configuration.GetConnectionString("DefaultConnection");

        services.AddDbContext<AppDbContext>(options =>
        {
            options.UseSqlServer(connectionString, sql =>
                sql.MigrationsAssembly(typeof(AppDbContext).Assembly.FullName));
            // RefreshToken/UserRole → User (soft-deleted) is intentional; a filtered-out user simply
            // yields a null navigation, which the refresh handler treats as an invalid token.
            options.ConfigureWarnings(w =>
                w.Ignore(CoreEventId.PossibleIncorrectRequiredNavigationWithQueryFilterInteractionWarning));
        });

        services.AddScoped<IApplicationDbContext>(sp => sp.GetRequiredService<AppDbContext>());
        services.AddSingleton<IDateTimeProvider, DateTimeProvider>();
        services.AddScoped<DatabaseInitializer>();

        // Builds public storefront email links (verification/reset) from configuration.
        services.AddSingleton<IStorefrontUrlBuilder, StorefrontUrlBuilder>();

        // Auto-generated storefront product rows: New Arrivals / Best Sellers / On Sale / Featured (WO-98).
        services.AddScoped<IAutoGeneratedRowService, AutoGeneratedRowService>();

        // Authentication / security (WO-1).
        services.Configure<JwtOptions>(configuration.GetSection("Jwt"));
        services.AddSingleton<RsaKeyProvider>();
        services.AddSingleton<IJwtTokenService, JwtTokenService>();
        services.AddSingleton<IPasswordHasher, PasswordHasher>();

        // API key authentication for machine-to-machine callers (WO-95).
        services.AddScoped<IApiKeyService, ApiKeyService>();

        // Credential vault (WO-7): deployment-specific Data Protection key ring persisted outside the DB.
        var dpKeysPath = configuration["DataProtection:KeysPath"];
        if (string.IsNullOrWhiteSpace(dpKeysPath))
            dpKeysPath = "keys/dataprotection";
        services.AddDataProtection()
            .SetApplicationName("VSky.ECommerce")
            .PersistKeysToFileSystem(new DirectoryInfo(dpKeysPath));

        services.AddHttpClient();

        // Carrier clients decompress responses. FedEx returns its errors gzipped whether or not we ask,
        // and HttpClient does not decompress by default — so the body reached the log as binary noise and
        // a compressed success response would have failed to parse as JSON at all. The carriers are named
        // clients, so the handler is configured per name rather than globally.
        foreach (var carrierClient in new[] { "fedex", "dhl-express", "usps", "ups" })
        {
            services.AddHttpClient(carrierClient)
                .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
                {
                    AutomaticDecompression = DecompressionMethods.GZip
                        | DecompressionMethods.Deflate
                        | DecompressionMethods.Brotli,
                });
        }

        // Column protector (singleton so the cached EF model's encrypted-column converter stays valid).
        services.AddSingleton<ICredentialProtector, CredentialProtector>();
        services.AddScoped<ICredentialVault, CredentialVault>();

        // SMTP account management (WO-75).
        services.AddScoped<ISmtpTester, MailKitSmtpTester>();

        // Email enqueuer (WO-20): queues verification / password-reset emails for the dispatch worker.
        services.AddScoped<IEmailEnqueuer, EmailEnqueuer>();
        services.AddScoped<IEmailTemplateSender, EmailTemplateSender>();

        // Settings (WO-3): cached, audited platform settings.
        services.AddMemoryCache();
        services.AddScoped<ISettingsService, SettingsService>();

        // SEO (WO-57): sitemap.xml generation + cache, DB-backed robots.txt, product schema.org JSON-LD.
        services.AddScoped<ISeoService, SeoService>();

        // Audit-finding resolutions: currency auto-refresh (WO-90) + admin alerts (WO-75 AC-TEN-003.5).
        services.AddScoped<ICurrencyRateRefresher, CurrencyRateRefresher>();
        services.AddScoped<IAdminAlertService, AdminAlertService>();

        // Inventory service (WO-12): per-store stock tracking, decrement/restore/RMA hooks, low-stock alerts.
        services.AddScoped<IInventoryService, InventoryService>();

        // Order routing engine (WO-51): capability checks + geo-proximity store selection with fallback.
        services.AddScoped<IOrderRoutingEngine, OrderRoutingEngine>();

        // ---- Phase 3 commerce services ----
        // Pricing: discount evaluation + coupon validation/redemption (WO-24/25).
        services.AddScoped<IDiscountService, DiscountService>();
        services.AddScoped<ICouponService, CouponService>();
        // Multi-currency conversion (WO-26).
        services.AddScoped<ICurrencyService, CurrencyService>();
        // Localization: translated-content resolution with default-language fallback (WO-18).
        services.AddScoped<ITranslationService, VSky.Infrastructure.Localization.TranslationService>();
        // Customer roles: group pricing + catalog-access resolution (WO-22).
        services.AddScoped<ICustomerGroupService, VSky.Infrastructure.Customers.CustomerGroupService>();
        services.AddScoped<IStoreCreditService, VSky.Infrastructure.Customers.StoreCreditService>();
        // Shipping: custom-method + carrier rate aggregation (WO-40/43).
        services.AddScoped<ICarrierClient, DhlExpressCarrierClient>();
        services.AddScoped<ICarrierClient, UpsCarrierClient>();
        services.AddScoped<ICarrierClient, FedExCarrierClient>();
        services.AddScoped<ICarrierClient, UspsCarrierClient>();
        services.AddScoped<IShippingRateService, ShippingRateService>();
        services.AddScoped<IShippingOptionSelector, VSky.Infrastructure.Shipping.ShippingOptionSelector>();
        services.AddScoped<IShippingLabelService, VSky.Infrastructure.Shipping.ShippingLabelService>();
        // Tax: calculation service + provider clients with flat-rate fallback (WO-35/36).
        services.AddScoped<ITaxProviderClient, TaxJarClient>();
        services.AddScoped<ITaxProviderClient, StripeTaxClient>();
        services.AddScoped<ITaxCalculationService, TaxCalculationService>();
        services.AddScoped<INexusTracker, VSky.Infrastructure.Tax.NexusTracker>();
        // Payments: gateway router + adapters + expired-auth scanner (WO-32/33/34).
        services.AddScoped<IPaymentGatewayAdapter, StripeGatewayAdapter>();
        services.AddScoped<IPaymentGatewayAdapter, PaypalGatewayAdapter>();
        services.AddScoped<IPaymentGatewayAdapter, RazorpayGatewayAdapter>();
        services.AddScoped<IPaymentGatewayAdapter, SquareGatewayAdapter>();
        services.AddScoped<IPaymentGatewayAdapter, AuthorizeNetGatewayAdapter>();
        services.AddScoped<IPaymentGatewayAdapter, CodGatewayAdapter>();
        services.AddScoped<IPaymentGatewayAdapter, BankTransferGatewayAdapter>();
        services.AddScoped<IPaymentGatewayRouter, PaymentGatewayRouter>();
        services.AddScoped<IExpiredAuthorizationScanner, ExpiredAuthorizationScanner>();
        // Order documents: invoice + packing-slip PDFs (WO-47).
        services.AddScoped<IOrderDocumentService, OrderDocumentService>();
        // Checkout orchestrator: cart → routing → shipping → tax → discounts → payment → order (WO-30).
        services.AddScoped<ICheckoutOrchestrator, CheckoutOrchestrator>();
        // reCAPTCHA server-side verification for protected forms (WO-107).
        services.AddScoped<IRecaptchaVerifier, RecaptchaVerifier>();

        // File storage (WO-88): provider-agnostic service with Local + Azure Blob adapters.
        services.AddScoped<IFileStorageAdapter, LocalFilesystemAdapter>();
        services.AddScoped<IFileStorageAdapter, AzureBlobAdapter>();
        services.AddScoped<IFileStorage, FileStorageService>();
        // Central media library: short-lived prepared-upload store for the two-step flow (WO-122).
        services.AddSingleton<IMediaTempStore, VSky.Infrastructure.Storage.MediaTempStore>();

        // Background task scheduler (WO-4).
        services.AddSingleton<TaskScheduleRegistry>();
        services.AddSingleton<IBackgroundTaskStatusProvider>(sp => sp.GetRequiredService<TaskScheduleRegistry>());
        services.AddSingleton<IScheduledTask, AbandonedCartWorker>();
        services.AddSingleton<IScheduledTask, LowStockAlertWorker>();
        services.AddSingleton<IScheduledTask, TrackingSyncWorker>();
        services.AddSingleton<IScheduledTask, CurrencyRateRefreshWorker>();
        services.AddSingleton<IScheduledTask, ExpiredAuthorizationWorker>();
        services.AddSingleton<IScheduledTask, DatabaseCleanupWorker>();
        services.AddSingleton<IScheduledTask, AbandonedOrderCleanupWorker>();
        services.AddSingleton<IScheduledTask, VSky.Infrastructure.BackgroundTasks.Workers.WebhookDispatchWorker>();
        services.AddSingleton<IScheduledTask, VSky.Infrastructure.BackgroundTasks.Workers.EmailDispatchWorker>();
        // Webhooks: domain event bus that enqueues signed deliveries (WO-5).
        services.AddScoped<IDomainEventBus, VSky.Infrastructure.Webhooks.DomainEventBus>();
        services.AddHostedService<TaskSchedulerService>();

        return services;
    }
}
