using Microsoft.AspNetCore.Mvc;
using VSky.API.Authorization;
using VSky.Application.Common.Authorization;
using VSky.Application.Common.Interfaces;
using VSky.Application.Features.FeaturedContent;
using VSky.Application.Features.StorefrontCatalog;
using VSky.Domain.Enums;

namespace VSky.API.Controllers;

/// <summary>
/// Manage storefront featured content (WO-98): the featured-product flag + ordering, the featured-category
/// flag, and a preview of the auto-generated rows the dynamic home (WO-96) renders.
/// </summary>
[Route("api/admin/featured")]
[RequireModule(Modules.Cms)]
public class AdminFeaturedContentController : ApiControllerBase
{
    /// <summary>Set (or clear) a product's featured flag and optional display order (route id wins over the body).</summary>
    [HttpPut("products/{productId:guid}")]
    public async Task<ActionResult<FeaturedProductDto>> SetProductFeatured(
        Guid productId, [FromBody] SetProductFeaturedCommand command)
        => Ok(await Mediator.Send(command with { ProductId = productId }));

    /// <summary>Rewrite the featured-product ordering to match the supplied id sequence.</summary>
    [HttpPut("products/reorder")]
    public async Task<IActionResult> ReorderFeaturedProducts([FromBody] ReorderFeaturedProductsCommand command)
    {
        await Mediator.Send(command);
        return NoContent();
    }

    /// <summary>Set (or clear) a category's featured flag (route id wins over the body).</summary>
    [HttpPut("categories/{categoryId:guid}")]
    public async Task<ActionResult<FeaturedCategoryDto>> SetCategoryFeatured(
        Guid categoryId, [FromBody] SetCategoryFeaturedCommand command)
        => Ok(await Mediator.Send(command with { CategoryId = categoryId }));

    /// <summary>List all featured products in curated order (admin manage-featured screen).</summary>
    [HttpGet("products")]
    public async Task<ActionResult<IReadOnlyList<FeaturedProductDto>>> ListFeaturedProducts()
        => Ok(await Mediator.Send(new ListFeaturedProductsQuery()));

    /// <summary>List all featured categories in curated order.</summary>
    [HttpGet("categories")]
    public async Task<ActionResult<IReadOnlyList<FeaturedCategoryDto>>> ListFeaturedCategories()
        => Ok(await Mediator.Send(new ListFeaturedCategoriesQuery()));

    /// <summary>Preview an auto-generated product row (as the storefront home would resolve it) for the admin editor.</summary>
    [HttpGet("preview")]
    public async Task<ActionResult<IReadOnlyList<StorefrontProductSummaryDto>>> Preview(
        [FromServices] IAutoGeneratedRowService rows,
        [FromQuery] AutoGeneratedRowRule rule = AutoGeneratedRowRule.NewArrivals,
        [FromQuery] int max = 10,
        CancellationToken cancellationToken = default)
        => Ok(await rows.ResolveAsync(rule, max, cancellationToken));
}
